### ISSUE TITLE
data file missing

### ISSUE THREAD

**Issue by Zhanghahah** [doyle-lab-ucla/tosylate-reduction-ML#1]
hello,

Thanks for your sharing.  However, i found that some source files were missing in `h_learning.ipython.` . (`pd.read_csv(s3+"datasets/unprocessed_train_set.csv", index_col = 0)` stored in aws). this will make this work unreproduced. Could you please share meta data you mentioned in `h_learning.ipython`. Thanks a lot!

**Comment by danielsmin** [comment]
Hello, it seems to work on our end. Please make sure to install boto3/s3fs to be able to access s3 buckets in aws. If you can provide more specific error messages I can help you in that way!
